version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - docker build -t myrepo .
      - docker tag myrepo:latest 567921641031.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
  post_build:
    commands:
      - docker push 567921641031.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
      - printf '[{"name":"mytask","imageUri":"%s"}]' 567921641031.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
