version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t myrepo .
      - docker tag myrepo:latest 567921641031.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
  post_build:
    commands:
      - docker push 567921641031.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
      - printf '[{"name":"mytask","imageUri":"%s"}]' 567921641031.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
